-- 企画申し込みURLトークン
CREATE TABLE event_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_id INT NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);
